"""Profile markdown from the profile JSON, the tag registry and the DB numbers.

Tags are resolved through the registry at render time: merged names show under
their canonical tag, dropped names are hidden, names not classified yet are
marked. Stat and price tables come from the DB on every render.
"""

from pathlib import Path

from app.knowledge import stats
from app.knowledge.profile import Note
from app.knowledge.tags import Registry

HEADER = "<!-- Generated by `make knowledge-run`. Do not edit. -->\n"


def _src(item: dict, notes: dict[str, Note]) -> str:
    links = []
    for i, sid in enumerate(item.get("sources", []), 1):
        if sid == "stats":
            links.append("stats")
        elif (n := notes.get(sid)):
            links.append(f"[{n.date[5:]}]({n.url})")
    return ", ".join(links)


def _statement(item: dict, notes: dict[str, Note]) -> str:
    until = f", until {item['until']}" if item.get("until") else ""
    return f"- {escape_dollar(item['text'])} ({item['kind']}, {item['date']}{until}; {_src(item, notes)})"


def resolved_tags(doc: dict, reg: Registry, gate=None) -> dict[str, list[dict]]:
    """channel -> [{name, detail, until, unclassified}], canonical names, merged duplicates.

    `gate(rule, sources) -> (ok, reason)` is the code check of category tags
    (knowledge.categories.allowed); tags it refuses go to the "blocked" key.
    """
    seen: dict[str, dict] = {}
    blocked: list[dict] = []
    for t in doc.get("tags", []):
        if reg.is_dropped(t["name"]):
            continue
        tag = reg.resolve(t["name"])
        if gate and tag and tag.rule:
            ok, reason = gate(tag.rule, t.get("sources", []))
            if not ok:
                if all(b["name"] != tag.name for b in blocked):
                    blocked.append({"name": tag.name, "reason": reason})
                continue
        name = tag.name if tag else t["name"]
        channel = tag.channel if tag else t["channel"]
        if name in seen:
            e = seen[name]
            if t.get("detail") and t["detail"] not in e["detail"]:
                e["detail"] = "; ".join(x for x in (e["detail"], t["detail"]) if x)
            e["until"] = e["until"] or t.get("until", "")
            e["sources"] += [x for x in t.get("sources", []) if x not in e["sources"]]
            continue
        seen[name] = {"name": name, "channel": channel, "detail": t.get("detail", ""),
                      "until": t.get("until", ""), "unclassified": tag is None, "raw": t["name"],
                      "kind": tag.kind if tag else None, "sources": list(t.get("sources", []))}
    out: dict[str, list[dict]] = {"current": [], "durable": []}
    for e in seen.values():
        out.setdefault(e["channel"], []).append(e)
    out["blocked"] = blocked
    return out


def newest_first(items: list[dict]) -> list[dict]:
    """Statements by date, newest on top. Same date keeps the LLM's order."""
    return sorted(items, key=lambda i: i.get("date") or "", reverse=True)


def escape_dollar(text: str) -> str:
    """Markdown viewers read "$38 ... $12" as LaTeX math; escape the dollar sign."""
    return text.replace("\\$", "$").replace("$", "\\$")


def _tag(e: dict) -> str:
    extra = [x for x in (e["detail"], f"until {e['until']}" if e["until"] else "") if x]
    mark = " (unclassified)" if e["unclassified"] else ""
    return f"`{e['name']}`{mark}" + (f" ({escape_dollar('; '.join(extra))})" if extra else "")


def profile_md(doc: dict, numbers: stats.PlayerNumbers, reg: Registry, notes: dict[str, Note],
               level: int = 1, gate=None, category_block: str = "") -> str:
    p = doc["player"]
    h = "#" * level
    out = [f"{h} {p['name']} ({p['team'] or 'FA'}, {p['position'] or '?'})", "",
           stats.stat_table(numbers, newest_first=True), "", stats.price_table(numbers), ""]
    if category_block:
        out += ["<details><summary>Category profile (code)</summary>\n", category_block, "\n</details>\n"]
    for section in ("current", "durable"):
        out.append(f"**{section.capitalize()}**")
        out += [_statement(i, notes) for i in newest_first(doc.get(section, []))] or ["- none"]
        out.append("")
    tags = resolved_tags(doc, reg, gate)
    out.append("**Tags**")
    for ch in ("current", "durable"):
        out.append(f"- {ch.capitalize()}: " + (", ".join(_tag(e) for e in tags.get(ch, [])) or "none"))
    out += ["", f"**Note.** {escape_dollar(doc.get('note', ''))}", ""]
    if tags["blocked"]:
        out.append("<sub>Tags removed by the category check: "
                   + "; ".join(f"{b['name']} ({b['reason']})" for b in tags["blocked"]) + ".</sub>\n")
    if doc.get("rejected"):
        out.append(f"<details><summary>Rejected by the source check: {len(doc['rejected'])}</summary>\n")
        out += [f"- [{r['section']}] {r.get('text') or r.get('name')} (sources: {', '.join(r.get('bad_sources', [])) or 'none'})"
                for r in doc["rejected"]]
        out.append("\n</details>\n")
    out.append(f"<sub>{doc['note_count']} notes. Built {doc['built_at'][:10]} with {doc['llm'].get('model')} "
               f"{doc['llm'].get('effort')}, prompt v{doc['prompt_version']}.</sub>\n")
    return "\n".join(out)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + text, encoding="utf-8")


def team_md(doc: dict, numbers_block: str, reg: Registry, notes: dict[str, Note]) -> str:
    out = [f"# {doc['team']}", "", numbers_block, ""]
    for section in ("current", "durable"):
        out.append(f"**{section.capitalize()}**")
        out += [_statement(i, notes) for i in newest_first(doc.get(section, []))] or ["- none"]
        out.append("")
    tags = resolved_tags(doc, reg, gate=lambda rule, sources: (False, "player tag"))
    out.append("**Tags**")
    for ch in ("current", "durable"):
        out.append(f"- {ch.capitalize()}: " + (", ".join(_tag(e) for e in tags.get(ch, [])) or "none"))
    out += ["", f"**Note.** {escape_dollar(doc.get('note', ''))}", ""]
    if doc.get("rejected"):
        out.append(f"<sub>Rejected by the source check: {len(doc['rejected'])}.</sub>\n")
    out.append(f"<sub>{doc['note_count']} notes. Built {doc['built_at'][:10]} with {doc['llm'].get('model')} "
               f"{doc['llm'].get('effort')}, team prompt v{doc['prompt_version']}.</sub>\n")
    return "\n".join(out)
