"""Render the knowledge base markdown from the per-video JSON notes.

Pure apart from file writes. Generated folders are wiped and rewritten on every
render, so never hand-edit files under videos/, players/, teams/ or the
generated top-level pages. Hand-edited: aliases.json only.
"""

from collections import defaultdict
from pathlib import Path

from app.experts.match import Matcher
from app.experts.transcript import fmt_ts

GENERATED_DIRS = ("videos", "players", "teams")
GENERATED_FILES = ("README.md", "methods.md", "claims.md", "_unmatched.md")
HEADER = "<!-- Generated by `make expert-digest`. Do not edit. -->\n"


def link(video_id: str, seconds: int | None) -> str:
    t = int(seconds or 0)
    return f"[{fmt_ts(t)}](https://youtu.be/{video_id}?t={t})"


def video_file(doc: dict) -> str:
    return f"{doc['video']['upload_date']}-{doc['video']['id']}.md"


def _line(doc: dict, item: dict, text: str | None = None, with_date: bool = True) -> str:
    v = doc["video"]
    parts = [f"- {v['upload_date']} " if with_date else "- ", link(v["id"], item.get("seconds")), " ",
             text if text is not None else item["text"]]
    if item.get("value_hint"):
        parts.append(f" Value: {item['value_hint'].strip().rstrip('.')}.")
    parts.append(f' ([video](../videos/{video_file(doc)}))' if with_date else "")
    parts.append(f'\n  > "{item["quote"]}"')
    return "".join(parts)


def _ok(items: list[dict]) -> list[dict]:
    return [i for i in items if i.get("verified")]


def render(docs: list[dict], matcher: Matcher, out: Path) -> dict:
    """Write all pages under `out`. Returns counts."""
    docs = sorted(docs, key=lambda d: (d["video"]["upload_date"], d["video"]["id"]), reverse=True)
    for d in GENERATED_DIRS:
        (out / d).mkdir(parents=True, exist_ok=True)
        for f in (out / d).glob("*.md"):
            f.unlink()

    players: dict[str, list] = defaultdict(list)  # slug -> [(doc, item)]
    player_meta: dict[str, object] = {}
    teams: dict[str, list] = defaultdict(list)
    unmatched: dict[str, list] = defaultdict(list)  # name -> [(doc, item)]
    fuzzy: dict[tuple, list] = defaultdict(list)  # (name, matched name) -> [(doc, item)]

    for doc in docs:
        for item in _ok(doc["player_notes"]):
            p, how = matcher.player_how(item["player"], item.get("said_as", ""), item.get("team", ""))
            if p is None:
                unmatched[item["player"]].append((doc, item))
                continue
            if how in ("fuzzy", "learned"):
                fuzzy[(item["player"], p.name)].append((doc, item))
            players[p.slug].append((doc, item))
            player_meta[p.slug] = p
        for item in _ok(doc["team_notes"]):
            t = matcher.team(item["team"])
            if t is None:
                unmatched[f"team: {item['team']}"].append((doc, item))
                continue
            teams[t].append((doc, item))
        _write(out / "videos" / video_file(doc), _video_page(doc, matcher))

    for slug, notes in players.items():
        p = player_meta[slug]
        _write(out / "players" / f"{slug}.md", _subject_page(f"{p.name} ({p.team or 'FA'})", notes))
    for team, notes in teams.items():
        _write(out / "teams" / f"{team}.md", _subject_page(team, notes))

    _write(out / "methods.md", _list_page("Methods and rules", "rules", docs,
                                         "General methods and strategy, newest video first."))
    _write(out / "claims.md", _list_page("Claims to check", "claims_to_check", docs,
                                        "Factual claims our stats data can confirm or refute."))
    _write(out / "_unmatched.md", _unmatched_page(unmatched, fuzzy))
    _write(out / "README.md", _index_page(docs, players, player_meta, teams))
    return {"videos": len(docs), "players": len(players), "teams": len(teams),
            "unmatched": len(unmatched), "fuzzy": len(fuzzy)}


def _write(path: Path, text: str) -> None:
    path.write_text(HEADER + text.rstrip() + "\n", encoding="utf-8")


def _subject_page(title: str, notes: list) -> str:
    durable = [n for n in notes if n[1].get("horizon") == "durable"]
    current = [n for n in notes if n[1].get("horizon") != "durable"]
    videos = len({d["video"]["id"] for d, _ in notes})
    lines = [f"# {title}", "", f"{len(notes)} notes from {videos} videos. Newest first.", ""]
    for name, group, hint in (
        ("Durable", durable, "Lasting traits: skills, category profile, injury history, style."),
        ("Current", current, "Can change soon: role, minutes, health, price, advice. Check the date."),
    ):
        lines += [f"## {name}", "", hint, ""]
        lines += [_line(d, i) for d, i in group] or ["None."]
        lines.append("")
    return "\n".join(lines)


def _video_page(doc: dict, matcher: Matcher) -> str:
    v = doc["video"]
    lines = [
        f"# {v['title']}", "",
        f"{v['channel']}, {v['upload_date']}, {v['duration']}. https://youtu.be/{v['id']}", "",
        "## Summary", "", doc["summary"], "", "## Rules and methods", "",
    ]
    lines += [_line(doc, i, with_date=False) for i in _ok(doc["rules"])] or ["None."]
    lines += ["", "## Players", ""]
    for i in _ok(doc["player_notes"]):
        p = matcher.player(i["player"], i.get("said_as", ""), i.get("team", ""))
        name = f"[{p.name}](../players/{p.slug}.md)" if p else f"{i['player']} (unmatched)"
        lines.append(_line(doc, i, f"**{name}** ({i['horizon']}): {i['text']}", with_date=False))
    lines += ["", "## Teams", ""]
    for i in _ok(doc["team_notes"]):
        t = matcher.team(i["team"])
        name = f"[{t}](../teams/{t}.md)" if t else f"{i['team']} (unmatched)"
        lines.append(_line(doc, i, f"**{name}** ({i['horizon']}): {i['text']}", with_date=False))
    lines += ["", "## Claims to check", ""]
    lines += [_line(doc, i, with_date=False) for i in _ok(doc["claims_to_check"])] or ["None."]
    bad = [(k, i) for k in ("rules", "player_notes", "team_notes", "claims_to_check")
           for i in doc[k] if not i.get("verified")]
    if bad:
        lines += ["", "## Unverified", "",
                  "The quote of these items was not found in the transcript. They are not used on other pages.", ""]
        lines += [f"- ({k}) {link(v['id'], i.get('seconds'))} {i['text']}\n  > \"{i['quote']}\"" for k, i in bad]
    return "\n".join(lines)


def _list_page(title: str, key: str, docs: list[dict], intro: str) -> str:
    lines = [f"# {title}", "", intro, ""]
    for doc in docs:
        items = _ok(doc[key])
        if not items:
            continue
        v = doc["video"]
        lines += [f"## {v['upload_date']} [{v['title']}](videos/{video_file(doc)})", ""]
        lines += [_line(doc, i, with_date=False) for i in items]
        lines.append("")
    return "\n".join(lines)


def _refs(notes: list) -> str:
    return ", ".join(link(d["video"]["id"], i.get("seconds")) for d, i in notes[:5])


def _unmatched_page(unmatched: dict, fuzzy: dict) -> str:
    lines = ["# Unmatched names", "",
             "Names from notes that are not in our players table or team list.",
             'To fix one, add it to `aliases.json` ("players": {"Wemby": "Victor Wembanyama"}) and re-render.', ""]
    for name, notes in sorted(unmatched.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        said = sorted({i.get("said_as", "") for _, i in notes} - {""})
        lines.append(f"- {name} ({len(notes)}){' said as: ' + ', '.join(said) if said else ''}. {_refs(notes)}")
    if not unmatched:
        lines.append("None.")
    lines += ["", "## Fuzzy matches", "",
              "Matched by last name, spelling or a learned nickname. Check them. A wrong one: add an alias in `players`.", ""]
    for (name, matched), notes in sorted(fuzzy.items()):
        said = sorted({i.get("said_as", "") for _, i in notes} - {""})
        lines.append(f"- {name} -> {matched} ({len(notes)}), said as: {', '.join(said)}. {_refs(notes)}")
    if not fuzzy:
        lines.append("None.")
    return "\n".join(lines)


def _index_page(docs, players, player_meta, teams) -> str:
    lines = ["# Expert knowledge base", "",
             "Notes from expert videos (M8 expert digest). Every note links to its timestamp and quotes the transcript.",
             "", "- [Methods and rules](methods.md)", "- [Claims to check](claims.md)",
             "- [Unmatched names](_unmatched.md)", "", "## Videos", "",
             "| Date | Video | Rules | Player notes | Unverified |", "|---|---|---|---|---|"]
    for d in docs:
        v = d["video"]
        total = sum(len(d[k]) for k in ("rules", "player_notes", "team_notes", "claims_to_check"))
        ok = sum(len(_ok(d[k])) for k in ("rules", "player_notes", "team_notes", "claims_to_check"))
        lines.append(f"| {v['upload_date']} | [{v['title']}](videos/{video_file(d)}) | "
                     f"{len(_ok(d['rules']))} | {len(_ok(d['player_notes']))} | {total - ok} |")
    lines += ["", "## Players", ""]
    ranked = sorted(players.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    lines += [f"- [{player_meta[s].name}](players/{s}.md) ({len(n)})" for s, n in ranked] or ["None."]
    lines += ["", "## Teams", ""]
    lines += [f"- [{t}](teams/{t}.md) ({len(n)})" for t, n in sorted(teams.items())] or ["None."]
    return "\n".join(lines)
