"""baseline leagues and teams

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 20:42:51.015652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sa.String(), nullable=False),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('draft_budget', sa.Integer(), nullable=True),
    sa.Column('draft_time', sa.String(), nullable=True),
    sa.Column('roster_positions', sa.JSON(), nullable=False),
    sa.Column('stat_categories', sa.JSON(), nullable=False),
    sa.Column('raw_settings', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_pk', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_pk'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('leagues')
    # ### end Alembic commands ###
