"""players, stats, market values, schedule

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 02:35:11.369495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_game_id', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('start_utc', sa.DateTime(), nullable=False),
    sa.Column('game_date_et', sa.Date(), nullable=False),
    sa.Column('home', sa.String(), nullable=False),
    sa.Column('away', sa.String(), nullable=False),
    sa.Column('neutral_site', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_game_id')
    )
    with op.batch_alter_table('nba_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_schedule_game_date_et'), ['game_date_et'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('name_key', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('identity_source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name_key'), ['name_key'], unique=False)

    op.create_table('player_external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    with op.batch_alter_table('player_external_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_external_ids_player_pk'), ['player_pk'], unique=False)

    op.create_table('player_market_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('auction_value', sa.Double(), nullable=True),
    sa.Column('average_cost', sa.Double(), nullable=True),
    sa.Column('average_pick', sa.Double(), nullable=True),
    sa.Column('percent_drafted', sa.Double(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=True),
    sa.Column('injury', sa.String(), nullable=True),
    sa.Column('injury_note', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'season')
    )
    with op.batch_alter_table('player_market_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_market_values_player_pk'), ['player_pk'], unique=False)

    op.create_table('player_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('gp', sa.Double(), nullable=False),
    sa.Column('fgm', sa.Double(), nullable=False),
    sa.Column('fga', sa.Double(), nullable=False),
    sa.Column('ftm', sa.Double(), nullable=False),
    sa.Column('fta', sa.Double(), nullable=False),
    sa.Column('tpm', sa.Double(), nullable=False),
    sa.Column('pts', sa.Double(), nullable=False),
    sa.Column('reb', sa.Double(), nullable=False),
    sa.Column('ast', sa.Double(), nullable=False),
    sa.Column('stl', sa.Double(), nullable=False),
    sa.Column('blk', sa.Double(), nullable=False),
    sa.Column('tov', sa.Double(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'season')
    )
    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_projections_player_pk'), ['player_pk'], unique=False)

    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('gp', sa.Double(), nullable=False),
    sa.Column('fgm', sa.Double(), nullable=False),
    sa.Column('fga', sa.Double(), nullable=False),
    sa.Column('ftm', sa.Double(), nullable=False),
    sa.Column('fta', sa.Double(), nullable=False),
    sa.Column('tpm', sa.Double(), nullable=False),
    sa.Column('pts', sa.Double(), nullable=False),
    sa.Column('reb', sa.Double(), nullable=False),
    sa.Column('ast', sa.Double(), nullable=False),
    sa.Column('stl', sa.Double(), nullable=False),
    sa.Column('blk', sa.Double(), nullable=False),
    sa.Column('tov', sa.Double(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'season')
    )
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_stats_player_pk'), ['player_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_season_stats_player_pk'))

    op.drop_table('player_season_stats')
    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_projections_player_pk'))

    op.drop_table('player_projections')
    with op.batch_alter_table('player_market_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_market_values_player_pk'))

    op.drop_table('player_market_values')
    with op.batch_alter_table('player_external_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_external_ids_player_pk'))

    op.drop_table('player_external_ids')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_name_key'))

    op.drop_table('players')
    with op.batch_alter_table('nba_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_schedule_game_date_et'))

    op.drop_table('nba_schedule')
    # ### end Alembic commands ###
