"""player game logs

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 17:44:25.282591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('home', sa.Boolean(), nullable=False),
    sa.Column('min', sa.Double(), nullable=False),
    sa.Column('fgm', sa.Double(), nullable=False),
    sa.Column('fga', sa.Double(), nullable=False),
    sa.Column('ftm', sa.Double(), nullable=False),
    sa.Column('fta', sa.Double(), nullable=False),
    sa.Column('tpm', sa.Double(), nullable=False),
    sa.Column('pts', sa.Double(), nullable=False),
    sa.Column('reb', sa.Double(), nullable=False),
    sa.Column('ast', sa.Double(), nullable=False),
    sa.Column('stl', sa.Double(), nullable=False),
    sa.Column('blk', sa.Double(), nullable=False),
    sa.Column('tov', sa.Double(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'game_id')
    )
    with op.batch_alter_table('player_game_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_logs_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_logs_player_pk'), ['player_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_logs_player_pk'))
        batch_op.drop_index(batch_op.f('ix_player_game_logs_game_date'))

    op.drop_table('player_game_logs')
    # ### end Alembic commands ###
