"""stat minutes

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 18:03:52.944956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min', sa.Double(), nullable=True))

    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.drop_column('min')

    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.drop_column('min')

    # ### end Alembic commands ###
