"""role sources and sync runs

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04 18:37:49.341290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_job'), ['job'], unique=False)

    op.create_table('team_win_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('wins', sa.Double(), nullable=False),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'season', 'team')
    )
    op.create_table('depth_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'season', 'team', 'slot', 'order')
    )
    with op.batch_alter_table('depth_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depth_charts_player_pk'), ['player_pk'], unique=False)

    op.create_table('player_minutes_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('mpg', sa.Double(), nullable=False),
    sa.Column('gp', sa.Double(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'season')
    )
    with op.batch_alter_table('player_minutes_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_minutes_projections_player_pk'), ['player_pk'], unique=False)

    with op.batch_alter_table('player_game_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_type', sa.String(), server_default='regular', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_logs', schema=None) as batch_op:
        batch_op.drop_column('season_type')

    with op.batch_alter_table('player_minutes_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_minutes_projections_player_pk'))

    op.drop_table('player_minutes_projections')
    with op.batch_alter_table('depth_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depth_charts_player_pk'))

    op.drop_table('depth_charts')
    op.drop_table('team_win_totals')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_job'))

    op.drop_table('sync_runs')
    # ### end Alembic commands ###
