"""knowledge tags

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-04 19:15:27.187499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('until', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('classified', sa.Boolean(), nullable=False),
    sa.Column('built_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_tags_player_pk'), ['player_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_tags_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_tags_team'), ['team'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_tags_team'))
        batch_op.drop_index(batch_op.f('ix_knowledge_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_knowledge_tags_player_pk'))

    op.drop_table('knowledge_tags')
    # ### end Alembic commands ###
