"""player advanced stats

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-05 00:54:47.527952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_advanced_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('gp', sa.Double(), nullable=False),
    sa.Column('usg_pct', sa.Double(), nullable=True),
    sa.Column('ts_pct', sa.Double(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'source', 'season')
    )
    with op.batch_alter_table('player_advanced_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_advanced_stats_player_pk'), ['player_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_advanced_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_advanced_stats_player_pk'))

    op.drop_table('player_advanced_stats')
    # ### end Alembic commands ###
