"""projection adjustments

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-05 09:16:44.580945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projection_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_pk', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mpg', sa.Double(), nullable=True),
    sa.Column('games_out', sa.Double(), nullable=True),
    sa.Column('late_games_out', sa.Double(), nullable=True),
    sa.Column('multipliers', sa.JSON(), nullable=False),
    sa.Column('floor', sa.JSON(), nullable=False),
    sa.Column('ceiling', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_pk'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pk', 'season', 'source')
    )
    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projection_adjustments_player_pk'), ['player_pk'], unique=False)

    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_projections', schema=None) as batch_op:
        batch_op.drop_column('extra')

    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projection_adjustments_player_pk'))

    op.drop_table('projection_adjustments')
    # ### end Alembic commands ###
