"""adjustment gp

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-05 09:47:15.377782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gp', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.drop_column('gp')

    # ### end Alembic commands ###
