"""adjustment usg and model

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-05 10:24:38.549497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usg', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection_adjustments', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('usg')

    # ### end Alembic commands ###
